services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: cookbook_sql
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  
  cookbook-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cookbook-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQL_SERVER=${DB_HOST}
      - SQL_DB=${DB_NAME}
      - SQL_USER=${DB_USER}
      - SQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:5046"
    depends_on:
      - sqlserver
    
volumes:
  mssql_data:
    
