services:
  
  postgres:
    image: postgres:17
    container_name: cookbook_pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  cookbook-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cookbook-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionString__DefaultConnection: ${ConnectionString__DefaultConnection}
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - postgres
    
volumes:
  postgres_data:
    
