name: Deploy with Docker Compose on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DB_ConnectionString__DefaultConnection: ${{DB_ConnectionString__DefaultConnection}}
      ASPNETCORE_ENVIRONMENT: ${{ASPNETCORE_ENVIRONMENT}}
      API_PORT: ${{API_PORT}}
      DB_USER: ${{DB_USER}}
      DB_PASSWORD: ${{DB_PASSWORD}}
      DB_NAME: ${{DB_NAME}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: debug
        run: ls -la

    
      - name: Stop and remove existing containers
        run: |
          docker compose -f docker-compose.prod.yml down

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
