name: Publish API with Docker on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t cookbook-api:latest .

      - name: Stop running container
        run: |
          docker stop cookbook-api || true
          docker rm cookbook-api || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name cookbook-api \
            -p 5046:8080 \
            -e ASPNETCORE_URLS=http://0.0.0.0:8080 \
            --restart unless-stopped \
            cookbook-api:latest
