name: Deploy with Docker Compose on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and remove existing containers
        working-directory: CookBook_Api
        run: |
          docker compose -f docker-compose.prod.yml down

      - name: Build and start containers
        working-directory: CookBook_Api
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
