name: Deploy with Docker Compose on Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    env:
      ConnectionString__DefaultConnection: ${{secrets.DB_ConnectionString__DefaultConnection}}
      ASPNETCORE_ENVIRONMENT: ${{secrets.ASPNETCORE_ENVIRONMENT}}
      API_PORT: ${{secrets.API_PORT}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: debug
        run: ls -la

    
      - name: Stop and remove existing containers
        run: |
          docker compose -f docker-compose.prod.yml down

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
