name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t cookbook-api:latest .

    # Optional: Run tests inside the image
    # - name: Run tests
    #   run: docker run --rm cookbook-api dotnet test

    # Optional: Push image
    # - name: Push Docker image
    #   run: docker tag cookbook-api yourusername/cookbook-api:latest && docker push yourusername/cookbook-api:latest
