name: Publish API for Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for linux-arm64
        run: dotnet publish -c Release -r linux-arm64 --self-contained false -o ./publish




