name: Run Tests of feature Branches

on:
  push:
    branches:
      - feature/**
      - Feature/**

jobs:
  feature-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image and run Unittests
        run: docker build -f Dockerfile.test . || exit 1